cache: yarn
language: node_js
node_js: 14
branches:
  only: main
install:
  - yarn
script:
  - yarn test
  - yarn build
deploy:
  keep-history: true
  local-dir: build
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  on:
    branch: main
  github-token:
    secure: Wu3szg+LbUo+U6wZXueNODuQGcLwcDzIjZhzElvtZ7kjWHEIzDjK6h/oyrlLG/NTLHYMw/fK76vaqYj7bFW6MYX/7qkSYl62L+LzU3RSaAz+elZitDErgtp6dcn+00xT9kqHKXiU5NiwSiJoPgofOWAPElau+scSXlg4AjyREZzDXmi/tO8kcxKEAXXaojvlGD0+P17yT+i2415nmbwTQEownMpUw0Ov25V4F3WgOKXol9MYFCY7bQeOaPticrGUychckA/kHM2PAFNxdP+35DETOk6sg/mViI/NlFcyA76TNov/ZcPKdUTB+UVKMqurYxOoNJqJHJM8vyOdB+Vwfc/sswsHVLixp1+mu/zQ3kqeB2LI2QmkmWTHsAlAFkoWjWeSW8zFRYvIGl837yauU7yANlQ3zw940L/5+/HMpE1CZL8uXsWBZS4/xlT7Hq0tM1RWJOZdDqwg8RyG4Ulp5YvFut47I/HEjgGm+Ce4rc1l3JMzuQGufQ0LXPE74ZMdYVK/YRzFNmv8zg3hiooxkj6/WZQugzCkbIjq90t4yqrS606VEIB6Z1e5ZNNUMJRax4n3Ysh4iwHJDgg7aipd/q+DU+1SBbFMyDfq3zQFzQr3ncw+ca7lsq85RhaGdZA5HtWydCqk0MDLri5V7Q2uPyxWWow87ikoVmOKxsQ4MgQ=
